name: 'Tag'
description: 'Tag release'
inputs:
  tag:
    required: true
    type: string
    default: false
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ${{ github.action_path }}/tag.sh ${{ inputs.tag }}
      shell: bash