name: Create Tag and Make Release

on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: false

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        if: ${{ inputs.tag == 'false' }}
        uses: martinbeentjes/npm-get-version-action@main

      - name: Set version string
        id: set-version
        if: ${{ inputs.tag == 'false' }}
        run: echo "VERSION=v${{ steps.package-version.outputs.current-version }}" >> $GITHUB_OUTPUT

      - name: Set tag
        id: set-tag
        run: echo "VERSION_TAG=${{ inputs.tag == 'false' && steps.set-version.outputs.VERSION || inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check_tag
        with:
          tag: "${{ steps.set-tag.outputs.VERSION_TAG }}"  

      - name: Create tag with input
        if: ${{ steps.check_tag.outputs.exists != 'true' }}
        uses: UserLeap/common-workflows/.github/actions/tag@main
        with:
          tag: '${{ steps.set-tag.outputs.VERSION_TAG }}'

      - name: Create release
        if: ${{ steps.check_tag.outputs.exists != 'true' }}
        uses: UserLeap/common-workflows/.github/actions/release@main
        with:
          tag: '${{ steps.set-tag.outputs.VERSION_TAG }}'
          release_url: '${{ inputs.release_url }}'
          token: '${{ secrets.GITHUB_TOKEN }}'