name: Create Tag and Make Release

on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: false

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        env:
          TAG:  v${{ inputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check_tag
        with:
          tag: "${{ env.TAG }}"  

      - name: Create tag with input
        if: ${{ inputs.tag != 'false' && steps.check_tag.outputs.exists != 'true' }}
        uses: UserLeap/common-workflows/.github/actions/tag@main
        env:
          TAG:  v${{ inputs.tag }}
        with:
          tag: '${{ env.TAG }}'

      - name: Create release
        env:
          TAG:  v${{ inputs.tag }}
        if: ${{ steps.check_tag.outputs.exists != 'true' }}
        uses: UserLeap/common-workflows/.github/actions/release@main
        with:
          tag: '${{ env.TAG }}'
          release_url: '${{ inputs.release_url }}'
          token: '${{ secrets.GITHUB_TOKEN }}'