name: Create Tag and Make Release

on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: false

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        env:
          TAG:  v${{ inputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check_tag
        with:
          tag: "${{ env.TAG }}"  

      - name: Create tag with input
        if: ${{ inputs.tag != 'false' && steps.check_tag.outputs.exists != 'true' }}
        env:
          TAG:  v${{ inputs.tag }}
        run: bash /home/runner/work/common-workflows/common-workflows/scripts/tag-and-release.sh tag ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }}

      - name: Create release
        env:
          TAG:  v${{ inputs.tag }}
        if: ${{ steps.check_tag.outputs.exists != 'true' }}
        run: bash /home/runner/work/common-workflows/common-workflows/scripts/tag-and-release.sh release ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }} ${{ inputs.release_url }}